# Generated by Django 4.2.8 on 2026-07-15 19:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_permisorol'),
    ]

    operations = [
        migrations.CreateModel(
            name='SriEmpresaConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruc', models.CharField(max_length=13, verbose_name='RUC')),
                ('razon_social', models.CharField(max_length=300, verbose_name='Razón Social')),
                ('nombre_comercial', models.CharField(blank=True, max_length=300, verbose_name='Nombre Comercial')),
                ('direccion', models.TextField(blank=True, verbose_name='Dirección')),
                ('contribuyente_especial', models.CharField(blank=True, max_length=4, verbose_name='Resolución Contribuyente Especial')),
                ('obligado_contabilidad', models.BooleanField(default=True, verbose_name='Obligado a llevar contabilidad')),
                ('ambiente', models.CharField(choices=[('1', 'Pruebas'), ('2', 'Producción')], default='1', max_length=1, verbose_name='Ambiente SRI')),
                ('certificado_p12', models.FileField(blank=True, help_text='Archivo .p12 del certificado de firma electrónica', null=True, upload_to='sri/certificados/', verbose_name='Certificado Digital (.p12)')),
                ('clave_certificado', models.CharField(blank=True, help_text='Contraseña del archivo .p12', max_length=255, verbose_name='Clave del Certificado')),
                ('estab_factura', models.CharField(default='001', max_length=3, verbose_name='Establecimiento (Facturas)')),
                ('emision_factura', models.CharField(default='001', max_length=3, verbose_name='Punto de Emisión (Facturas)')),
                ('secuencial_factura', models.PositiveIntegerField(default=1, verbose_name='Secuencial actual (Facturas)')),
                ('resolucion_sri', models.CharField(blank=True, help_text='Número de resolución de la autorización SRI (offline)', max_length=50, verbose_name='Resolución SRI')),
                ('fecha_caducidad', models.DateField(blank=True, help_text='Fecha de caducidad de la autorización SRI', null=True, verbose_name='Fecha de caducidad')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('empresa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sri_config', to='core.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Configuración SRI',
                'verbose_name_plural': 'Configuraciones SRI',
            },
        ),
        migrations.CreateModel(
            name='SriDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('01', 'Factura'), ('04', 'Nota de Crédito'), ('05', 'Nota de Débito'), ('06', 'Guía de Remisión'), ('07', 'Comprobante de Retención')], max_length=2, verbose_name='Tipo')),
                ('clave_acceso', models.CharField(max_length=49, unique=True, verbose_name='Clave de Acceso')),
                ('numero_documento', models.CharField(help_text='Formato: 001-001-000000001', max_length=20, verbose_name='N° Documento')),
                ('factura_origen_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID Factura Origen')),
                ('factura_origen_modelo', models.CharField(blank=True, max_length=100, verbose_name='Modelo Factura Origen')),
                ('xml_firmado', models.TextField(blank=True, verbose_name='XML Firmado')),
                ('xml_autorizado', models.TextField(blank=True, verbose_name='XML Autorizado')),
                ('numero_autorizacion', models.CharField(blank=True, max_length=50, verbose_name='N° Autorización SRI')),
                ('fecha_autorizacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Autorización')),
                ('ambiente', models.CharField(choices=[('1', 'Pruebas'), ('2', 'Producción')], max_length=1, verbose_name='Ambiente')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de envío'), ('ENVIADO', 'Enviado al SRI'), ('AUTORIZADO', 'Autorizado'), ('NO_AUTORIZADO', 'No autorizado'), ('ERROR', 'Error')], default='PENDIENTE', max_length=20, verbose_name='Estado')),
                ('mensajes', models.JSONField(blank=True, default=list, verbose_name='Mensajes SRI')),
                ('fecha_emision', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de emisión')),
                ('identificacion_comprador', models.CharField(blank=True, max_length=20, verbose_name='Identificación comprador')),
                ('razon_social_comprador', models.CharField(blank=True, max_length=300, verbose_name='Razón social comprador')),
                ('total_sin_impuestos', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total sin impuestos')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('empresa_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='sri.sriempresaconfig', verbose_name='Configuración SRI')),
            ],
            options={
                'verbose_name': 'Documento Electrónico',
                'verbose_name_plural': 'Documentos Electrónicos',
                'ordering': ['-created_at'],
            },
        ),
    ]
