# Generated by Django 6.0.6 on 2026-07-15 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sri', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sridocumento',
            name='archivo_xml_autorizado',
            field=models.FileField(blank=True, null=True, upload_to='sri/documentos/autorizados/', verbose_name='Archivo XML Autorizado'),
        ),
        migrations.AddField(
            model_name='sridocumento',
            name='archivo_xml_firmado',
            field=models.FileField(blank=True, null=True, upload_to='sri/documentos/firmados/', verbose_name='Archivo XML Firmado'),
        ),
    ]
