# Generated by Django 6.0.6 on 2026-07-15 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sri', '0002_sridocumento_archivo_xml_autorizado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sriempresaconfig',
            name='comercio_exterior',
            field=models.BooleanField(default=False, help_text='SI/NO - Marcar si la factura es de exportación', verbose_name='Comercio Exterior'),
        ),
        migrations.AddField(
            model_name='sriempresaconfig',
            name='inco_term_factura',
            field=models.CharField(blank=True, help_text='Término de negociación (ej: EXW, FOB, CIF)', max_length=50, verbose_name='Incoterm Factura'),
        ),
        migrations.AddField(
            model_name='sriempresaconfig',
            name='lugar_inco_term',
            field=models.CharField(blank=True, help_text='Lugar del término de negociación', max_length=100, verbose_name='Lugar Incoterm'),
        ),
        migrations.AddField(
            model_name='sriempresaconfig',
            name='pais_adquisicion',
            field=models.CharField(blank=True, help_text='Código ISO del país de adquisición', max_length=4, verbose_name='País de Adquisición'),
        ),
        migrations.AddField(
            model_name='sriempresaconfig',
            name='pais_destino',
            field=models.CharField(blank=True, help_text='Código ISO del país de destino', max_length=4, verbose_name='País Destino'),
        ),
        migrations.AddField(
            model_name='sriempresaconfig',
            name='pais_origen',
            field=models.CharField(blank=True, help_text='Código ISO del país de origen', max_length=4, verbose_name='País Origen'),
        ),
        migrations.AddField(
            model_name='sriempresaconfig',
            name='puerto_destino',
            field=models.CharField(blank=True, max_length=100, verbose_name='Puerto de Destino'),
        ),
        migrations.AddField(
            model_name='sriempresaconfig',
            name='puerto_embarque',
            field=models.CharField(blank=True, max_length=100, verbose_name='Puerto de Embarque'),
        ),
    ]
