# Generated by Django 6.0.6 on 2026-07-15 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sri', '0003_sriempresaconfig_comercio_exterior_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sriempresaconfig',
            name='tipo_contribuyente',
            field=models.CharField(choices=[('REGIMEN_GENERAL', 'Régimen General'), ('RIMPE_NEGOCIO_POPULAR', 'RIMPE - Negocio Popular'), ('RIMPE_EMPRENDEDOR', 'RIMPE - Emprendedor'), ('AGENTE_RETENCION', 'Agente de Retención'), ('CONTRIBUYENTE_ESPECIAL', 'Contribuyente Especial')], default='REGIMEN_GENERAL', max_length=30, verbose_name='Tipo de Contribuyente'),
        ),
    ]
