# Generated by Django 6.0.6 on 2026-07-16 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sri', '0004_sriempresaconfig_tipo_contribuyente'),
    ]

    operations = [
        migrations.AddField(
            model_name='sridocumento',
            name='secuencial',
            field=models.CharField(blank=True, help_text='Secuencial de 9 dígitos usado para este documento', max_length=9, verbose_name='Secuencial usado'),
        ),
    ]
