# Generated by Django 6.0.6 on 2026-06-06 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('cedula', models.CharField(max_length=20, unique=True, verbose_name='Cédula')),
                ('especialidad', models.CharField(choices=[('ODONTO_GENERAL', 'Odontología General'), ('ORTODONCIA', 'Ortodoncia'), ('ENDODONCIA', 'Endodoncia'), ('PERIODONCIA', 'Periodoncia'), ('CIRUGIA_ORAL', 'Cirugía Oral'), ('IMPLANTOLOGIA', 'Implantología'), ('PEDIATRIA', 'Odontopediatría'), ('ESTETICA', 'Odontología Estética'), ('RADIOLOGIA', 'Radiología Oral')], max_length=50, verbose_name='Especialidad')),
                ('registro_profesional', models.CharField(max_length=50, unique=True, verbose_name='Registro Profesional')),
                ('telefono', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Correo Electrónico')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
            ],
            options={
                'verbose_name': 'Médico',
                'verbose_name_plural': 'Médicos',
                'ordering': ['apellidos', 'nombres'],
            },
        ),
    ]
