# Generated by Django 4.2.8 on 2026-07-15 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_empresa_permiso_alter_backgroundtasklog_id_and_more'),
        ('medicos', '0002_medico_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='medico',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.empresa', verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='medico',
            name='cedula',
            field=models.CharField(max_length=20, verbose_name='Cédula'),
        ),
        migrations.AlterField(
            model_name='medico',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='medico',
            name='registro_profesional',
            field=models.CharField(max_length=50, verbose_name='Registro Profesional'),
        ),
        migrations.AlterUniqueTogether(
            name='medico',
            unique_together={('empresa', 'registro_profesional'), ('empresa', 'cedula')},
        ),
    ]
