# Generated by Django 6.0.6 on 2026-07-15 16:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundTaskLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarea', models.CharField(choices=[('RECORDATORIO_CITAS', 'Recordatorio de Citas'), ('FACTURACION_MENSUAL', 'Facturación Mensual'), ('RESPALDO_DB', 'Respaldo de Base de Datos'), ('LIMPIEZA_LOCKS', 'Limpieza de Locks'), ('ENVIAR_WHATSAPP', 'Envío de WhatsApp'), ('OTRA', 'Otra')], max_length=50, verbose_name='Tarea')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROCESO', 'En Proceso'), ('COMPLETADO', 'Completado'), ('ERROR', 'Error'), ('SIMULADO', 'Simulado')], default='PENDIENTE', max_length=20, verbose_name='Estado')),
                ('detalle', models.TextField(blank=True, verbose_name='Detalle / Resultado')),
                ('fecha_ejecucion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de ejecución')),
                ('duracion_segundos', models.FloatField(blank=True, null=True, verbose_name='Duración (segundos)')),
                ('ejecutado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Ejecutado por')),
            ],
            options={
                'verbose_name': 'Registro de Tarea',
                'verbose_name_plural': 'Registros de Tareas',
                'ordering': ['-fecha_ejecucion'],
            },
        ),
    ]
