# Generated by Django 4.2.8 on 2026-07-15 17:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('ruc', models.CharField(max_length=20, unique=True, verbose_name='RUC')),
                ('direccion', models.TextField(blank=True, verbose_name='Dirección')),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Correo electrónico')),
                ('subdominio', models.CharField(blank=True, help_text='Subdominio para acceso (ej: clinica1.odontsmart.com)', max_length=100, null=True, unique=True, verbose_name='Subdominio')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Permiso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del permiso')),
                ('codigo', models.CharField(help_text='Identificador único del permiso (ej: crear_pacientes)', max_length=100, unique=True, verbose_name='Código')),
                ('modulo', models.CharField(choices=[('PACIENTES', 'Pacientes'), ('MEDICOS', 'Médicos'), ('CITAS', 'Citas'), ('HISTORIAS', 'Historias Clínicas'), ('REPORTES', 'Reportes'), ('USUARIOS', 'Usuarios'), ('CONFIGURACION', 'Configuración'), ('TAREAS', 'Tareas Programadas')], max_length=50, verbose_name='Módulo')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Permiso',
                'verbose_name_plural': 'Permisos',
                'ordering': ['modulo', 'nombre'],
            },
        ),
        migrations.AlterField(
            model_name='backgroundtasklog',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='ConfiguracionEmpresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='empresas/logos/', verbose_name='Logo')),
                ('color_principal', models.CharField(default='#2563eb', help_text='Código hex, ej: #2563eb', max_length=7, verbose_name='Color principal')),
                ('color_secundario', models.CharField(default='#1e40af', help_text='Código hex, ej: #1e40af', max_length=7, verbose_name='Color secundario')),
                ('frase_pie', models.CharField(blank=True, default='Tu sonrisa, nuestra prioridad', max_length=200, verbose_name='Frase o lema')),
                ('moneda', models.CharField(default='USD', max_length=10, verbose_name='Moneda')),
                ('zona_horaria', models.CharField(default='America/Guayaquil', max_length=50, verbose_name='Zona horaria')),
                ('empresa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuracion', to='core.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Configuración de empresa',
                'verbose_name_plural': 'Configuraciones de empresa',
            },
        ),
        migrations.AddField(
            model_name='backgroundtasklog',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.empresa', verbose_name='Empresa'),
        ),
        migrations.CreateModel(
            name='PermisoUsuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concedido', models.BooleanField(default=True, help_text='Si está activo o denegado', verbose_name='Concedido')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de asignación')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permisos_usuarios', to='core.empresa', verbose_name='Empresa')),
                ('permiso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios_asignados', to='core.permiso', verbose_name='Permiso')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permisos_empresa', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Permiso de usuario',
                'verbose_name_plural': 'Permisos de usuarios',
                'unique_together': {('empresa', 'usuario', 'permiso')},
            },
        ),
    ]
