# Generated by Django 6.1.1 on 2026-09-09 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_permisorol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permiso',
            name='modulo',
            field=models.CharField(choices=[('PACIENTES', 'Pacientes'), ('MEDICOS', 'Médicos'), ('CITAS', 'Citas'), ('HISTORIAS', 'Historias Clínicas'), ('REPORTES', 'Reportes'), ('USUARIOS', 'Usuarios'), ('CONFIGURACION', 'Configuración'), ('TAREAS', 'Tareas Programadas'), ('FACTURACION', 'Facturación'), ('SRI', 'SRI')], max_length=50, verbose_name='Módulo'),
        ),
    ]
