# Generated by Django 6.0.6 on 2026-06-06 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='pacientes/', verbose_name='Foto del paciente'),
        ),
    ]
