# Generated by Django 6.0.6 on 2026-06-06 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0002_paciente_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='lugar',
            field=models.CharField(blank=True, max_length=100, verbose_name='Lugar'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='nacionalidad',
            field=models.CharField(blank=True, max_length=50, verbose_name='Nacionalidad'),
        ),
    ]
