# Generated by Django 4.2.8 on 2026-07-15 18:32

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_permisorol'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pacientes', '0005_paciente_empresa_alter_paciente_cedula_and_more'),
        ('medicos', '0003_medico_empresa_alter_medico_cedula_alter_medico_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proforma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(help_text='Se genera automáticamente (ej: PRO-0001)', max_length=20, unique=True, verbose_name='N° Proforma')),
                ('fecha_emision', models.DateField(auto_now_add=True, verbose_name='Fecha de emisión')),
                ('fecha_validez', models.DateField(help_text='Fecha hasta la cual el presupuesto tiene validez', verbose_name='Válido hasta')),
                ('items', models.JSONField(default=list, help_text='Lista de items: [{"descripcion": "...", "cantidad": 1, "precio_unitario": 0.00}]', verbose_name='Items')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Subtotal')),
                ('descuento_porcentaje', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Descuento %')),
                ('descuento_monto', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Descuento $')),
                ('impuesto_porcentaje', models.DecimalField(decimal_places=2, default=0, help_text='Porcentaje de IVA u otro impuesto', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Impuesto %')),
                ('impuesto_monto', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Impuesto $')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada'), ('VENCIDA', 'Vencida'), ('FACTURADA', 'Facturada')], default='PENDIENTE', max_length=20, verbose_name='Estado')),
                ('notas', models.TextField(blank=True, help_text='Condiciones, observaciones, etc.', verbose_name='Notas')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='Versión')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.empresa', verbose_name='Empresa')),
                ('medico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proformas', to='medicos.medico', verbose_name='Médico')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proformas', to='pacientes.paciente', verbose_name='Paciente')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proformas_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
            ],
            options={
                'verbose_name': 'Proforma',
                'verbose_name_plural': 'Proformas',
                'ordering': ['-fecha_emision', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(help_text='Se genera automáticamente (ej: FAC-0001)', max_length=20, unique=True, verbose_name='N° Factura')),
                ('fecha_emision', models.DateField(auto_now_add=True, verbose_name='Fecha de emisión')),
                ('fecha_pago', models.DateField(blank=True, null=True, verbose_name='Fecha de pago')),
                ('items', models.JSONField(default=list, help_text='Lista de items: [{"descripcion": "...", "cantidad": 1, "precio_unitario": 0.00}]', verbose_name='Items')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Subtotal')),
                ('descuento_porcentaje', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Descuento %')),
                ('descuento_monto', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Descuento $')),
                ('impuesto_porcentaje', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Impuesto %')),
                ('impuesto_monto', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Impuesto $')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total')),
                ('forma_pago', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TARJETA_CREDITO', 'Tarjeta de Crédito'), ('TARJETA_DEBITO', 'Tarjeta de Débito'), ('TRANSFERENCIA', 'Transferencia Bancaria'), ('CHEQUE', 'Cheque'), ('OTRO', 'Otro')], default='EFECTIVO', max_length=20, verbose_name='Forma de pago')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PAGADA', 'Pagada'), ('ANULADA', 'Anulada')], default='PENDIENTE', max_length=20, verbose_name='Estado')),
                ('notas', models.TextField(blank=True, verbose_name='Notas')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='Versión')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.empresa', verbose_name='Empresa')),
                ('medico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facturas', to='medicos.medico', verbose_name='Médico')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facturas', to='pacientes.paciente', verbose_name='Paciente')),
                ('proforma', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facturas', to='facturacion.proforma', verbose_name='Proforma origen')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facturas_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
                'ordering': ['-fecha_emision', '-id'],
            },
        ),
    ]
