# Generated by Django 6.0.6 on 2026-06-06 20:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('CREAR', 'Creación'), ('EDITAR', 'Edición'), ('ELIMINAR', 'Eliminación'), ('LOGIN', 'Inicio de sesión')], max_length=20, verbose_name='Acción')),
                ('modelo', models.CharField(max_length=50, verbose_name='Modelo')),
                ('objeto_id', models.PositiveIntegerField(blank=True, null=True)),
                ('descripcion', models.CharField(max_length=255, verbose_name='Descripción')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Actividad',
                'verbose_name_plural': 'Actividades',
                'ordering': ['-fecha'],
            },
        ),
    ]
