# Generated by Django 6.0.6 on 2026-07-15 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0002_alter_cita_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='version',
            field=models.PositiveIntegerField(default=1, help_text='Número de versión para control de concurrencia optimista', verbose_name='Versión'),
        ),
    ]
