# Generated by Django 6.1.1 on 2026-09-10 01:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0004_cita_empresa_alter_cita_id'),
        ('facturacion', '0002_servicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='servicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citas', to='facturacion.servicio', verbose_name='Servicio'),
        ),
    ]
