# Generated by Django 6.0.6 on 2026-06-06 20:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medicos', '0002_medico_user'),
        ('pacientes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriaClinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enfermedades', models.TextField(blank=True, help_text='Diabetes, hipertensión, cardiopatías, etc.', verbose_name='Enfermedades sistémicas')),
                ('alergias', models.TextField(blank=True, help_text='Medicamentos, alimentos, látex, etc.', verbose_name='Alergias')),
                ('medicamentos', models.TextField(blank=True, help_text='Medicamentos que toma actualmente', verbose_name='Medicamentos actuales')),
                ('tipo_sangre', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3, verbose_name='Tipo de sangre')),
                ('fumador', models.BooleanField(default=False, verbose_name='Fumador')),
                ('alcohol', models.BooleanField(default=False, verbose_name='Consume alcohol')),
                ('embarazo', models.BooleanField(default=False, verbose_name='Embarazada')),
                ('observaciones_habitos', models.TextField(blank=True, verbose_name='Observaciones de hábitos')),
                ('antecedentes_familiares', models.TextField(blank=True, help_text='Enfermedades relevantes en la familia', verbose_name='Antecedentes familiares')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('paciente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='historia', to='pacientes.paciente', verbose_name='Paciente')),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
            ],
            options={
                'verbose_name': 'Historia Clínica',
                'verbose_name_plural': 'Historias Clínicas',
            },
        ),
        migrations.CreateModel(
            name='Evolucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha de consulta')),
                ('motivo', models.TextField(verbose_name='Motivo de consulta')),
                ('diagnostico', models.TextField(blank=True, verbose_name='Diagnóstico')),
                ('tratamiento', models.TextField(blank=True, verbose_name='Tratamiento / Procedimiento')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('medico', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='medicos.medico', verbose_name='Médico')),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
                ('historia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evoluciones', to='historias.historiaclinica', verbose_name='Historia')),
            ],
            options={
                'verbose_name': 'Evolución',
                'verbose_name_plural': 'Evoluciones',
                'ordering': ['-fecha'],
            },
        ),
    ]
