# Generated by Django 6.0.6 on 2026-06-06 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historias', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historiaclinica',
            name='enfermedades',
        ),
        migrations.RemoveField(
            model_name='historiaclinica',
            name='medicamentos',
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='cardiacos',
            field=models.BooleanField(default=False, verbose_name='Problemas cardíacos'),
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='diabetes',
            field=models.BooleanField(default=False, verbose_name='Diabetes'),
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='hipertension',
            field=models.BooleanField(default=False, verbose_name='Hipertensión'),
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='medicacion',
            field=models.BooleanField(default=False, verbose_name='Toma medicación'),
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='observaciones_medicas',
            field=models.TextField(blank=True, help_text='Detalles adicionales sobre las condiciones marcadas', verbose_name='Observaciones médicas'),
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='alergias',
            field=models.BooleanField(default=False, verbose_name='Alergias'),
        ),
    ]
