# Generated by Django 6.0.6 on 2026-06-06 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historias', '0002_remove_historiaclinica_enfermedades_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historiaclinica',
            name='alergia_drogas',
            field=models.BooleanField(default=False, verbose_name='¿Es alérgico a alguna droga?'),
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='aspirina',
            field=models.BooleanField(default=False, verbose_name='¿Toma seguido aspirina y/o anticoagulante?'),
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='cicatrizacion',
            field=models.BooleanField(default=False, verbose_name='¿Cicatriza bien?'),
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='diabetes_controlado',
            field=models.CharField(blank=True, max_length=100, verbose_name='¿Está controlado? ¿Con qué?'),
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='exceso_saliva',
            field=models.BooleanField(default=False, verbose_name='¿Tiene exceso de saliva en la anestesia?'),
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='frecuencia_aspirina',
            field=models.CharField(blank=True, max_length=100, verbose_name='¿Con qué frecuencia?'),
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='sangrado',
            field=models.BooleanField(default=False, verbose_name='¿Sangra mucho?'),
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='cardiacos',
            field=models.BooleanField(default=False, verbose_name='¿Tiene algún problema cardíaco?'),
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='diabetes',
            field=models.BooleanField(default=False, verbose_name='¿Es diabético?'),
        ),
    ]
