# Generated by Django 6.0.6 on 2026-06-06 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historias', '0003_historiaclinica_alergia_drogas_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Odontograma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dientes', models.JSONField(default=dict, verbose_name='Estado de dientes')),
                ('prestaciones', models.JSONField(default=dict, verbose_name='Prestaciones')),
                ('protesis_fija', models.BooleanField(default=False, verbose_name='Prótesis fija')),
                ('protesis_removible', models.BooleanField(default=False, verbose_name='Prótesis removible')),
                ('coronas', models.BooleanField(default=False, verbose_name='Coronas')),
                ('cantidad_dientes_existentes', models.PositiveIntegerField(blank=True, null=True, verbose_name='Cantidad de dientes existentes')),
                ('presencia_sarro', models.BooleanField(default=False, verbose_name='Presencia de sarro')),
                ('enfermedad_periodontal', models.BooleanField(default=False, verbose_name='Enfermedad periodontal')),
                ('historia', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='odontograma', to='historias.historiaclinica', verbose_name='Historia')),
            ],
            options={
                'verbose_name': 'Odontograma',
                'verbose_name_plural': 'Odontogramas',
            },
        ),
    ]
