# Generated by Django 6.0.6 on 2026-06-06 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historias', '0004_odontograma'),
    ]

    operations = [
        migrations.AddField(
            model_name='historiaclinica',
            name='consentimiento',
            field=models.BooleanField(default=False, verbose_name='Paciente acepta el tratamiento'),
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='consentimiento_cedula',
            field=models.CharField(blank=True, max_length=20, verbose_name='Cédula de identidad'),
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='consentimiento_direccion',
            field=models.TextField(blank=True, verbose_name='Dirección'),
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='consentimiento_fecha',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de consentimiento'),
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='consentimiento_paciente',
            field=models.CharField(blank=True, max_length=200, verbose_name='Nombre del paciente'),
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='diagnostico_presuntivo',
            field=models.TextField(blank=True, verbose_name='Diagnóstico presuntivo'),
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='observaciones',
            field=models.TextField(blank=True, verbose_name='Observaciones'),
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='plan_tratamiento',
            field=models.TextField(blank=True, verbose_name='Plan de tratamiento'),
        ),
    ]
