# Generated by Django 6.0.6 on 2026-06-06 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historias', '0005_historiaclinica_consentimiento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historiaclinica',
            name='consentimiento_medico',
            field=models.CharField(blank=True, max_length=200, verbose_name='Médico que solicita el consentimiento'),
        ),
    ]
