# Generated by Django 6.0.6 on 2026-06-06 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historias', '0006_historiaclinica_consentimiento_medico'),
    ]

    operations = [
        migrations.AddField(
            model_name='evolucion',
            name='consentimiento_acepta',
            field=models.BooleanField(default=False, verbose_name='Paciente acepta el tratamiento'),
        ),
        migrations.AddField(
            model_name='evolucion',
            name='consentimiento_fecha',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de consentimiento'),
        ),
        migrations.AddField(
            model_name='evolucion',
            name='consentimiento_medico',
            field=models.CharField(blank=True, max_length=200, verbose_name='Médico que informa'),
        ),
    ]
