# Generated by Django 6.0.6 on 2026-06-06 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historias', '0007_evolucion_consentimiento_acepta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evolucion',
            name='proxima_consulta',
            field=models.DateField(blank=True, null=True, verbose_name='Próxima consulta'),
        ),
        migrations.AddField(
            model_name='evolucion',
            name='proxima_consulta_nota',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nota para la próxima consulta'),
        ),
    ]
