# Generated by Django 6.0.6 on 2026-06-12 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historias', '0008_evolucion_proxima_consulta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evolucion',
            name='costo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Costo del tratamiento'),
        ),
    ]
