# Generated by Django 6.0.6 on 2026-07-15 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historias', '0009_evolucion_costo'),
    ]

    operations = [
        migrations.AddField(
            model_name='evolucion',
            name='version',
            field=models.PositiveIntegerField(default=1, help_text='Número de versión para control de concurrencia optimista', verbose_name='Versión'),
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='version',
            field=models.PositiveIntegerField(default=1, help_text='Número de versión para control de concurrencia optimista', verbose_name='Versión'),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='version',
            field=models.PositiveIntegerField(default=1, help_text='Número de versión para control de concurrencia optimista', verbose_name='Versión'),
        ),
    ]
