# Generated by Django 6.1.1 on 2026-09-10 01:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0002_servicio'),
        ('historias', '0011_evolucion_empresa_historiaclinica_empresa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evolucion',
            name='servicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evoluciones', to='facturacion.servicio', verbose_name='Servicio'),
        ),
    ]
